# Generated by Django 4.0.4 on 2022-05-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_user_address_alter_user_email_id_and_more'),
        ('services_details', '0002_alter_service_details_service_detail_name'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION', models.CharField(blank=True, max_length=50, null=True)),
                ('ANSWER', models.CharField(blank=True, max_length=50, null=True)),
                ('POINTS', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_question', to='client.user')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_question', to='services_details.service_details')),
            ],
        ),
        migrations.DeleteModel(
            name='master_question',
        ),
    ]
