# Generated by Django 4.0.4 on 2022-05-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_service_service_name_delete_service_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_DETAIL_NAME', models.CharField(max_length=25)),
                ('SERVICE_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_detail', to='services.service')),
            ],
        ),
    ]
