# Generated by Django 4.0 on 2022-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='STATUS',
            field=models.IntegerField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')]),
        ),
    ]
