# Generated by Django 4.0 on 2022-03-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
