# Generated by Django 4.0 on 2022-03-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_delete_contact_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='STATUS',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=25),
        ),
    ]
