# Generated by Django 4.0 on 2022-03-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_question',
            name='SD_ID',
        ),
        migrations.RemoveField(
            model_name='service_detail',
            name='SERVICE_ID',
        ),
        migrations.RemoveField(
            model_name='sub_question',
            name='QUESTION_ID',
        ),
        migrations.RemoveField(
            model_name='sub_question',
            name='SD_ID',
        ),
        migrations.DeleteModel(
            name='document',
        ),
        migrations.DeleteModel(
            name='master_question',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='service_detail',
        ),
        migrations.DeleteModel(
            name='sub_question',
        ),
    ]
