# Generated by Django 4.0 on 2022-03-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_delete_contact_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RATINGS', models.CharField(max_length=25)),
                ('COMMENT', models.CharField(max_length=25)),
                ('L_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='client.user')),
            ],
        ),
    ]
