# Generated by Django 4.0 on 2022-03-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='L_ID',
            new_name='client',
        ),
    ]
