# Generated by Django 4.0 on 2022-03-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=25)),
                ('EMAIL', models.CharField(max_length=25)),
                ('NUMBER', models.IntegerField()),
                ('MESSAGE', models.TextField(max_length=25)),
            ],
        ),
    ]
