# Generated by Django 4.0 on 2022-03-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='EMAIL',
            field=models.EmailField(max_length=25),
        ),
    ]
