# Generated by Django 4.0.4 on 2022-05-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='MESSAGE',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='NAME',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='NUMBER',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
