# Generated by Django 4.0 on 2022-03-30 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_NAME', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='service_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_DETAIL_NAME', models.CharField(max_length=25)),
                ('SERVICE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_detail', to='services.service')),
            ],
        ),
    ]
