# Generated by Django 4.0.4 on 2022-05-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_details_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='SERVICE_NAME',
            field=models.CharField(choices=[('IELTS Inquiry', 'IELTS Inquiry'), ('Immigration Visa', 'Immigration Visa'), ('Non-Immigration Visa', 'Non-Immigration Visa'), ('Visitor Visa', 'Visitor Visa'), ('Student Visa', 'Student Visa'), ('Business Visa', 'Business Visa'), ('Permanent Residence', 'Permanent Residence')], max_length=25),
        ),
        migrations.DeleteModel(
            name='service_details',
        ),
    ]
