# Generated by Django 4.0.4 on 2022-05-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0008_login'),
        ('services', '0003_alter_service_service_name_delete_service_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOCUMENT_NAME', models.CharField(max_length=20)),
                ('DOCUMENT_FILE', models.FileField(blank=True, default='', null=True, upload_to='profile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='client.user')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='services.service')),
            ],
        ),
    ]
